import { useEffect } from 'react';

/**
 * useAutoHedgeName — hedge-level counterpart to `useAutoNameFromPreset`.
 *
 * The regular auto-name hook sources everything from a mounted leg's
 * BotFormProvider (`useBotFormState`), which throws outside a leg. A hedge
 * bot's name lives on the outer HedgeBotFormProvider and must auto-fill
 * even when no leg is mounted (e.g. the Hedge tab), so this hook takes all
 * of its inputs as arguments and reads/writes the hedge-scoped
 * `hedgeName` / `setHedgeName` instead.
 *
 * Behaviour mirrors the original: in create mode only, when the long leg's
 * pair is known, it composes `{longLegPair} {preset|botType} {date}` and
 * writes it — but only if the current name is blank, the bare `New Bot`
 * default, or a value that looks auto-generated. Anything the user typed is
 * left untouched.
 */

/** Escape a label so it can be embedded safely inside a RegExp. */
const escapeRegExp = (value: string): string =>
  value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/** Local calendar date as `YYYY-MM-DD` (ISO date, no time component). */
const todayIso = (): string => {
  const d = new Date();
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
};

interface UseAutoHedgeNameArgs {
  /** 'create' | 'edit' — only auto-fill in create mode. */
  mode: string;
  /**
   * The long leg's selected pair, published only by the long leg. Null
   * until the long leg has been visited (Manual) or mounted (Quick); the
   * name stays blank until then.
   */
  longLegPair: string | null;
  /**
   * Number of pairs on the long leg. When > 1 the prefix becomes
   * `{longLegPair} +{n-1}` (e.g. `BTCUSDT +4`), matching the regular
   * bots' multi-pair naming. Defaults to 1 (single pair).
   */
  longLegPairCount?: number;
  /** The currently-selected hedge preset (Quick), or null (Manual). */
  activePreset: { label: string } | null | undefined;
  /** All hedge preset labels, used to detect auto-generated names. */
  presetLabels: ReadonlyArray<string>;
  /**
   * Hedge bot type label used when no preset is active (e.g. 'Hedge DCA',
   * 'Hedge Combo').
   */
  botTypeLabel: string;
  /** Current shared hedge name. */
  hedgeName: string;
  /** Setter for the shared hedge name. */
  setHedgeName: (next: string) => void;
}

export const useAutoHedgeName = ({
  mode,
  longLegPair,
  longLegPairCount = 1,
  activePreset,
  presetLabels,
  botTypeLabel,
  hedgeName,
  setHedgeName,
}: UseAutoHedgeNameArgs): void => {
  useEffect(() => {
    if (mode !== 'create') return;
    if (!longLegPair) return;
    const currentName = (hedgeName ?? '').trim();

    const prefix =
      longLegPairCount > 1
        ? `${longLegPair} +${longLegPairCount - 1}`
        : longLegPair;
    const middle = activePreset?.label ?? botTypeLabel;
    const next = `${prefix} ${middle} ${todayIso()}`;
    if (next === currentName) return;

    const knownLabels = [...presetLabels, botTypeLabel];
    const looksAutoGenerated =
      !currentName ||
      currentName === 'New Bot' ||
      knownLabels.some((label) =>
        new RegExp(`\\s${escapeRegExp(label)}\\s\\d{4}-\\d{2}-\\d{2}$`).test(
          currentName
        )
      ) ||
      // Legacy "{pair} {presetLabel}" names (before dates were appended).
      presetLabels.some((label) => currentName.endsWith(` ${label}`));
    if (!looksAutoGenerated) return;

    setHedgeName(next);
  }, [
    mode,
    longLegPair,
    longLegPairCount,
    activePreset,
    presetLabels,
    botTypeLabel,
    hedgeName,
    setHedgeName,
  ]);
};
